Revert "Use <linux/eventpoll.h> to implement <sys/epoll.h>."
This reverts commit 893fd97cdcfbb040c938acac42658c885da879ee.

Reverted to fix compiling issues on mido:
bionic/libc/include/sys/epoll.h:67:8: error: redefinition of 'epoll_event'

Change-Id: Ib499f005c5590afbf71400ff9ea935f97debd118